<div class="sidabar-unit sidabar-unit-top">
    <h4 class="sidabar-unit-title">TOP 5 PRODUCTS</h4>
    <div class="sb-top">
        <ul class="sb-top-list">
            <li class="sb-top-item">
                <a href="" class="sb-top-link">
                    <img src="<?php echo $this->getSkinUrl('images/ex/little-item.png') ?>" alt="" class="sb-top-item-pic">
                    <div class="sb-top-item-data">
                        <span class="sb-top-item-title">Red Dress</span>
                        <span class="sb-top-item-price">25$</span>
                    </div>
                </a>
                <a href="" class="sb-top-item-buy">Buy</a>
            </li>
            <li class="sb-top-item">
                <a href="" class="sb-top-link">
                    <img src="<?php echo $this->getSkinUrl('images/ex/little-item.png') ?>" alt="" class="sb-top-item-pic">
                    <div class="sb-top-item-data">
                        <span class="sb-top-item-title">Red Dress</span>
                        <span class="sb-top-item-price">25$</span>
                    </div>
                </a>
                <a href="" class="sb-top-item-buy">Buy</a>
            </li>
            <li class="sb-top-item">
                <a href="" class="sb-top-link">
                    <img src="<?php echo $this->getSkinUrl('images/ex/little-item.png') ?>" alt="" class="sb-top-item-pic">
                    <div class="sb-top-item-data">
                        <span class="sb-top-item-title">Red Dress</span>
                        <span class="sb-top-item-price">25$</span>
                    </div>
                </a>
                <a href="" class="sb-top-item-buy">Buy</a>
            </li>
            <li class="sb-top-item">
                <a href="" class="sb-top-link">
                    <img src="<?php echo $this->getSkinUrl('images/ex/little-item.png') ?>" alt="" class="sb-top-item-pic">
                    <div class="sb-top-item-data">
                        <span class="sb-top-item-title">Red Dress</span>
                        <span class="sb-top-item-price">25$</span>
                    </div>
                </a>
                <a href="" class="sb-top-item-buy">Buy</a>
            </li>
            <li class="sb-top-item">
                <a href="" class="sb-top-link">
                    <img src="<?php echo $this->getSkinUrl('images/ex/little-item.png') ?>" alt="" class="sb-top-item-pic">
                    <div class="sb-top-item-data">
                        <span class="sb-top-item-title">Red Dress</span>
                        <span class="sb-top-item-price">25$</span>
                    </div>
                </a>
                <a href="" class="sb-top-item-buy">Buy</a>
            </li>
        </ul>
    </div>
</div>
