<ul class="site-hdr-main-menu">
    <li class="site-hdr-menuitem">
        <a href="<?php echo Mage::getUrl('colection/'); ?>">COLLECTION</a>
        <div class="site-hdr-menu-dropdown">
            <div class="site-hdr-wrap">
                <?php echo $this->getChildHtml('topMenu') ?>
                <div class="site-hdr-menu-additional">
                    <strong class="site-hdr-menudrop-title">WHAT’S NEW ?</strong>
                    <?php echo $this->getChildHtml('header_menu_additional') ?>
                </div>
            </div>
        </div>
    </li>
    <li class="site-hdr-menuitem"><a href="<?php echo Mage::getUrl('about-magento-demo-store/'); ?>">ABOUT</a></li>
    <li class="site-hdr-menuitem"><a href="<?php echo Mage::getUrl('sale/'); ?>">SALE</a></li>
    <li class="site-hdr-menuitem"><a href="<?php echo Mage::getUrl('blog/'); ?>">BLOG</a></li>
    <li class="site-hdr-menuitem"><a href="<?php echo Mage::getUrl('contact/'); ?>">CONTACT</a></li>
</ul>
