<ul class="site-hdr-main-menu">
    <li class="site-hdr-menuitem"><a href="<?php echo Mage::getUrl('colection/'); ?>">COLLECTION</a></li>
    <li class="site-hdr-menuitem"><a href="<?php echo Mage::getUrl('about-magento-demo-store/'); ?>">ABOUT</a></li>
    <li class="site-hdr-menuitem"><a href="<?php echo Mage::getUrl('sale/'); ?>">SALE</a></li>
    <li class="site-hdr-menuitem"><a href="<?php echo Mage::getUrl('blog/'); ?>">BLOG</a></li>
    <li class="site-hdr-menuitem"><a href="<?php echo Mage::getUrl('contact/'); ?>">CONTACT</a></li>
</ul>
